config/routes.rb
Rails.application.routes.draw do
	resources :students, :only => [:index, :show]
	resources :contracts, :only => [:index, :show]
	devise_for :users
	#resources :users_admin, :controller => 'users'
	#resources :transactions
	#resources :products do 
	#  get :autocomplete_brand_name, :on => :collection
	#end	

	#apis
	namespace :api do
		namespace :v1 do
			resources :users, :only => [:index, :show] do 
				resources :students, :only => [:index, :show, :create, :update, :destroy]
				resources :contracts, :only => [:index, :show, :create, :update, :destroy]
			end
		end
	end

	get 'static/index'
	get 'admin' => 'admin#index'
	get 'admin/users'
	get 'search' => 'static#search'

	authenticated :user do
		root 'students#index', as: 'authenticated_root'
	end

	root 'static#index'

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user
	belongs_to :head_of_house
	has_many :transactions

	extend FriendlyId
	friendly_id :name, use: :slugged

	def self.search(search)
	  where('name LIKE ?', "%#{search}%")
	end
end

app/controllers/api/v1/students_controller.rb
class Api::V1::StudentsController < ApplicationController
    respond_to :json
    #before_action :deny

	def deny
		redirect_to root_path unless user_signed_in?
	end

    def index
        @students = Student.where('user_id like ?', params[:user_id]).where('status like ?', '%active')
        render json: @students
    end

    def show
        @student = Student.where(:user_id=>params[:user_id]).where(:id=>params[:id])
        render json: @student
    end

    def create 
        @student = Student.new(student_params)

        if @student.save
            render json: @student, status: 201
        else
            render json: { errors: error.message }, status: 422
        end
    end

    def update
        @student = Student.where(:user_id=>params[:user_id]).where(:id=>params[:id]).first

        if @student.update(student_params)
            render json: @student, status: 201
        else
            render json: { errors: error.message }, state: 422
        end
    end

    def destroy
        @student = Student.where(:user_id=>params[:user_id]).where(:id=>params[:id]).first

        @student.destroy
        head 204 
    end

    private
        def student_params
            params.permit(:name, :address, :city, :state, :state, :zip, :status, :rank, :size, :trail, :phone, :age, :gender, :email, :slug, :user_id, :head_of_houses_id)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :find_student, only: [:show, :edit, :update, :destroy]
	before_action :deny
	layout 'student'

	def deny
		redirect_to root_path unless user_signed_in? or admin_signed_in?
	end

	def index
		@students = Student.where(user_id: current_user).where('status like ?', '%active').paginate(:page => params[:page], :per_page => 10).order(:name)

		@contractTotal = HeadOfHouse.all().where(user_id: current_user).count
		@totalStudents = Student.where(user_id: current_user).where('status like ?', '%active').count
	end

	def show
		@pos = Student.friendly.find(params[:id]).transactions
	end

	private
		def find_student
			@student = Student.friendly.find(params[:id])
		end

		def student_params
			params.require(:student).permit(:name, :address, :city, :state, :state, :zip, :status, :rank, :size, :amount, :trail, :phone, :age, :gender, :email, :slug, :shared)
		end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |s| %>
  <div class='name'>
    <p>
      <%= s.label :name %>
      <%= s.text_field :name %>
    </p>
    <p>
      <%= s.label :phone %>
      <%= s.text_field :phone %>
    </p>

  </div>

  <div class='name'>
    <p>
      <%= s.label :address %>
      <%= s.text_field :address %>
    </p>

    <p>
      <%= s.label :city %>
      <%= s.text_field :city %>
    </p>

  </div>

  <div class='name'>
    <p>
      <%= s.label :gender %>
      <%= s.select(:gender, options_for_select([['Male', 'Male'], ['Women', 'Women']], @student.gender)) %>
    </p>

    <p>
    <%= s.label :rank %>
    <%= s.select(:rank, options_for_select([
                                              ['White', "white"], ['Orange', 'orange'],
                                              ['Yellow', 'yellow'], ['Camo', 'camo'],
                                              ['Green', 'green'], ['Purple', 'purple'],
                                              ['Blue', 'blue'], ['Brown Rec', 'brown rec'],
                                              ['Brown Dec', 'brown dec'], ['Red Rec', 'red rec'],
                                              ['Red Dec', 'red dec'], ['Rec Black', 'rec black'],
                                              ['1st degree', '1st degree'], ['2nd degree', '2nd degree'],
                                              ['3rd degree', '3rd degree'], ['4th Degree', '4th degree']], @student.rank)) %>
    </p>
  </div>

  <div class='name'>

    <p>
      <%= s.label :email %>
      <%= s.text_field :email %>
    </p>

    <p>
      <%= s.label :zip %>
      <%= s.text_field :zip %>
    </p>

    <p>
      <%= s.label :age %>
      <%= s.text_field :age %>
    </p>

    <p>
      <%= s.label :size %>
      <%= s.text_field :size %>
    </p>
  </div>

  <div class='contact_info'>
    <p>
      <%= s.label :amount %>
      <%= s.text_field :amount %>
    </p>
    <p>
      <%= s.label :status %>
      <%= s.select(:status, options_for_select([['Prospect', 'trail'],['Active', 'active'], ['Hold', 'hold'], ['Inactive', 'quit']], @student.status)) %>
    </p>
  </div>

  <div class="name hidden">
    <p>
      <%= s.label :trail %>
      <%= s.text_field :trail %>
    </p>
  </div>

  <%= s.submit :class => 'button' %>
<% end %>

app/views/students/edit.html.erb
<div class='add_wrapper student'>
  <h1>Edit</h1>
  <%= render 'form' %>
  <%= link_to 'Delete', student_path(@student), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button alert' %>
</div>

app/views/students/index.html.erb
<h1>Students</h2>
    <div class="ui grid">
    <div class="row">
    <div class="ten wide column">
      <div class="ui top attached tabular menu">
        <a class="item active">
          Active List
        </a>
        <a class="item">
          Holds
        </a>
      </div>
      <student-cmp user-id="<%= current_user.id %>"></student-cmp>
      </div>

      <div class="four wide column ui segment dark">
        <h1>Amount</h1>
        <p>Total Students: <%= @totalStudents %></p>
        <p>Total Contracts: <%= @contractTotal %></p>
      </div>
      </div>
      </div>
  
  <%# render :partial => 'static/search' %>

app/views/students/new.html.erb
<div class='add_wrapper student'>
  <h1>Add New Student</h1>
  <%= render 'form' %>
</div>

app/views/students/new.js.erb
$('#new').hide();

app/views/students/show.html.erb
<div class="row student">
	<div class="student_main">
		<div class="student_name">
			<h1><%= @student.name %></h1><%= link_to 'Edit', edit_student_path %>
		</div>
		<div class="student_row">
			<h3>Status</h3>
			<p><%= @student.status %></p>
		</div>
		<div class="student_row">
			<h3>Age</h3>
			<p><%= @student.age %></p>
		</div>
		<div class="student_row">
			<h3>Shared</h3>
			<p><%= @student.shared %></p>
		</div>
	</div>
	<div class="student_studio">
		<h2>Studio Info</h2>
		<div class="student_row">
			<h3>Amount</h3>
			<p><%= @student.amount %></p>
		</div>
		<div class="student_row">
			<h3>Status</h3>
			<p><%= @student.status %></p>
		</div>
		<div class="student_row">
			<h3>Rank</h3>
			<p><%= @student.rank %></p>
		</div>
		<div class="student_row">
			<h3>Size</h3>
			<p><%= @student.size %></p>
		</div>
		<div class="student_row">
			<h3>Address</h3>
			<p><%= @student.address %></p>
		</div>
		<div class="student_row">
			<h3>Phone</h3>
			<p><%= @student.phone %></p>
		</div>
	</div>
	<!--<div class="student_info">
		<h3>PoS History</h3>
		<% @pos.each do |pos| %>
			<p> Item name: <%= pos.name %> | Price: $<%= pos.price %> | <%= pos.created_at.strftime("%B %d, %Y") %></p>
		<% end %>			
	</div>-->
</div>