config/routes.rb
Rails.application.routes.draw do
	resources :students, :only => [:index, :show]
	resources :contracts, :only => [:index, :show]
	devise_for :users
	#resources :users_admin, :controller => 'users'
	#resources :transactions
	#resources :products do 
	#  get :autocomplete_brand_name, :on => :collection
	#end	

	#apis
	namespace :api do
		namespace :v1 do
			resources :users, :only => [:index, :show] do 
				resources :students, :only => [:index, :show, :create, :update, :destroy]
				resources :contracts, :only => [:index, :show, :create, :update, :destroy]
			end
		end
	end

	get 'static/index'
	get 'admin' => 'admin#index'
	get 'admin/users'
	get 'search' => 'static#search'

	authenticated :user do
		root 'students#index', as: 'authenticated_root'
	end

	root 'static#index'

end

app/models/head_of_house.rb
class HeadOfHouse < ActiveRecord::Base
  belongs_to :user
  has_many :students
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user
	belongs_to :head_of_house
	has_many :transactions

	extend FriendlyId
	friendly_id :name, use: :slugged

	def self.search(search)
	  where('name LIKE ?', "%#{search}%")
	end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :student
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # If you need to add free registration later :registerable -> add to devise line
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :students
  has_many :head_of_houses
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :deny
	layout 'student'

	def deny
		redirect_to root_path unless current_user.admin?
	end

	def index
		@user = User.all()
		@total = @user.count()
	end

	def users
		@users = User.all()
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new

		if @user.save
			redirect_to root_path
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    layout 'student'
    
    def index

    end

    def show

    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'student'

  def new
   @product = Product.new
  end

  def create
   @product = Product.new(product_params)

   if @product.save
     redirect_to @product
   else
     render 'new'
   end
  end

  def show
    @product = Product.find(params[:id])
  end


  private

   def product_params
    params.require(:product).permit(:name, :price, :item_number)
   end


end

app/controllers/registrations_controller.rb
# class RegistrationsController < Devise::RegistrationsController
#   # disable default no_authentication action
#   skip_before_action :require_no_authentication, only: [:new, :create, :cancel]
#
#   protected
#
#   # The default sign_up method signs in new user upon creation
#   # I just commented it out so you can see what the default method looks like
#   def sign_up(resource_name, resource)
#     # sign_in(resource_name, resource)
#   end
# end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	layout 'student'
	def holds
		@students = Student.where(user_id: current_user).where('status like ?', '%hold').paginate(:page => params[:page], :per_page => 20)

		@precent = 0.03
		@total = Student.where(user_id: current_user).where('status like ?', '%hold').sum(:amount)
		@fees = Student.where(user_id: current_user).where('status like ?', '%hold').count(:amount)
		@totalFees = @fees * 0.69
		@totalPercent = @total * @precent
		@grandTotal = @total - @totalPercent - @totalFees.round(2)
	end

	def inactive
		@students = Student.where(user_id: current_user).where('status like ?', '%quit').paginate(:page => params[:page], :per_page => 20)
	end

	def trails
		@students = Student.where(user_id: current_user).where('status like ?', '%trail').paginate(:page => params[:page], :per_page => 20)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'student', :only => :search
  helper_method :resource_name, :resource, :devise_mapping
  
  def index
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def search
		if params[:search]
			@search = Student.search(params[:search])
		else
			'nothing'
		end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :find_student, only: [:show, :edit, :update, :destroy]
	before_action :deny
	layout 'student'

	def deny
		redirect_to root_path unless user_signed_in? or admin_signed_in?
	end

	def index
		@students = Student.where(user_id: current_user).where('status like ?', '%active').paginate(:page => params[:page], :per_page => 10).order(:name)

		@contractTotal = HeadOfHouse.all().where(user_id: current_user).count
		@totalStudents = Student.where(user_id: current_user).where('status like ?', '%active').count
	end

	def show
		@pos = Student.friendly.find(params[:id]).transactions
	end

	private
		def find_student
			@student = Student.friendly.find(params[:id])
		end

		def student_params
			params.require(:student).permit(:name, :address, :city, :state, :state, :zip, :status, :rank, :size, :amount, :trail, :phone, :age, :gender, :email, :slug, :shared)
		end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  layout 'student'
  autocomplete :products, :name, :full => true

  def index
    @transactions = Transaction.all
  end

  def new
   @product = Product.all
   @student = Student.where(user_id: current_user)
   @transaction = Transaction.new

  end

  def create
   @transaction = Transaction.new(transaction_params)

   if @transaction.save
     redirect_to root_path
   else 
     render 'new'
   end

  end



  private

    def transaction_params
      params.require(:transaction).permit(:name, :price, :student_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :deny
  layout 'student'

  def deny
		redirect_to root_path unless current_user.admin?
	end

  def index
      @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
      @user = User.new
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/admin'
    else
      render root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/new.html.erb
<div class="row student">
  <h1>Add New Product</h1>
  <%= form_for @product do |p| %>

    <%= p.label :name %>
    <%= p.text_field :name %>

    <%= p.label :price %>
    <%= p.text_field :price %>

    <%= p.submit  %>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row student">
  <h2><%= @product.name %></h2>
  <p><%= @product.price %></p>
</div>

app/views/users/edit.html.erb
<div class="row">
  <h1>Add new User</h1>
  <%= form_for @user, url: users_admin_path(@user) do |f| %>

    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="actions">
      <%= f.submit "Edit User", :class => 'button radius' %>
    </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
  <h1>Add new User</h1>
  <%= form_for @user, url: users_admin_index_path(@user) do |f| %>

    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username %>
    </div>

    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <h1><%= @user.username %></h1>
  <h5><%= @user.email %></h5>
  <%= link_to 'Edit', edit_users_admin_path(@user), :class => 'button' %>
  <%= link_to 'Delete', users_admin_path(@user), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button alert' %>
</div>