config/routes.rb
Rails.application.routes.draw do
	resources :students, :only => [:index, :show]
	resources :contracts, :only => [:index, :show]
	devise_for :users
	#resources :users_admin, :controller => 'users'
	#resources :transactions
	#resources :products do 
	#  get :autocomplete_brand_name, :on => :collection
	#end	

	#apis
	namespace :api do
		namespace :v1 do
			resources :users, :only => [:index, :show] do 
				resources :students, :only => [:index, :show, :create, :update, :destroy]
				resources :contracts, :only => [:index, :show, :create, :update, :destroy]
			end
		end
	end

	get 'static/index'
	get 'admin' => 'admin#index'
	get 'admin/users'
	get 'search' => 'static#search'

	authenticated :user do
		root 'students#index', as: 'authenticated_root'
	end

	root 'static#index'

end

app/models/head_of_house.rb
class HeadOfHouse < ActiveRecord::Base
  belongs_to :user
  has_many :students
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user
	belongs_to :head_of_house
	has_many :transactions

	extend FriendlyId
	friendly_id :name, use: :slugged

	def self.search(search)
	  where('name LIKE ?', "%#{search}%")
	end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :student
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # If you need to add free registration later :registerable -> add to devise line
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :students
  has_many :head_of_houses
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :deny
	layout 'student'

	def deny
		redirect_to root_path unless current_user.admin?
	end

	def index
		@user = User.all()
		@total = @user.count()
	end

	def users
		@users = User.all()
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new

		if @user.save
			redirect_to root_path
		end
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    layout 'student'
    
    def index

    end

    def show

    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'student'

  def new
   @product = Product.new
  end

  def create
   @product = Product.new(product_params)

   if @product.save
     redirect_to @product
   else
     render 'new'
   end
  end

  def show
    @product = Product.find(params[:id])
  end


  private

   def product_params
    params.require(:product).permit(:name, :price, :item_number)
   end


end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	layout 'student'
	def holds
		@students = Student.where(user_id: current_user).where('status like ?', '%hold').paginate(:page => params[:page], :per_page => 20)

		@precent = 0.03
		@total = Student.where(user_id: current_user).where('status like ?', '%hold').sum(:amount)
		@fees = Student.where(user_id: current_user).where('status like ?', '%hold').count(:amount)
		@totalFees = @fees * 0.69
		@totalPercent = @total * @precent
		@grandTotal = @total - @totalPercent - @totalFees.round(2)
	end

	def inactive
		@students = Student.where(user_id: current_user).where('status like ?', '%quit').paginate(:page => params[:page], :per_page => 20)
	end

	def trails
		@students = Student.where(user_id: current_user).where('status like ?', '%trail').paginate(:page => params[:page], :per_page => 20)
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  layout 'student', :only => :search
  helper_method :resource_name, :resource, :devise_mapping
  
  def index
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def search
		if params[:search]
			@search = Student.search(params[:search])
		else
			'nothing'
		end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :find_student, only: [:show, :edit, :update, :destroy]
	before_action :deny
	layout 'student'

	def deny
		redirect_to root_path unless user_signed_in? or admin_signed_in?
	end

	def index
		@students = Student.where(user_id: current_user).where('status like ?', '%active').paginate(:page => params[:page], :per_page => 10).order(:name)

		@contractTotal = HeadOfHouse.all().where(user_id: current_user).count
		@totalStudents = Student.where(user_id: current_user).where('status like ?', '%active').count
	end

	def show
		@pos = Student.friendly.find(params[:id]).transactions
	end

	private
		def find_student
			@student = Student.friendly.find(params[:id])
		end

		def student_params
			params.require(:student).permit(:name, :address, :city, :state, :state, :zip, :status, :rank, :size, :amount, :trail, :phone, :age, :gender, :email, :slug, :shared)
		end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  layout 'student'
  autocomplete :products, :name, :full => true

  def index
    @transactions = Transaction.all
  end

  def new
   @product = Product.all
   @student = Student.where(user_id: current_user)
   @transaction = Transaction.new

  end

  def create
   @transaction = Transaction.new(transaction_params)

   if @transaction.save
     redirect_to root_path
   else 
     render 'new'
   end

  end



  private

    def transaction_params
      params.require(:transaction).permit(:name, :price, :student_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :deny
  layout 'student'

  def deny
		redirect_to root_path unless current_user.admin?
	end

  def index
      @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
      @user = User.new
  end

  def edit
      @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/admin'
    else
      render root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to admin_users_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reports/holds.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <div class="row">
      <div class="large-8 large columns">
        <%# @totalFees %>
        <div class="header">
          <h1>Students On Hold</h1>
        </div>
        <table>
          <thead>
            <tr>
              <th>Student Name</th>
              <th class='rank_row'>Rank</th>
              <th class='rank_row'>Size</th>
              <th class='rank_row'>Age</th>
              <th class='address_row'>Address</th>
              <th class='phone_row'>Phone</th>
              <th class='amount_row'>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
              <tr>
                <td><%=  link_to student.name, student_path(student) %> </td>
                <td class='rank_row'><%=  student.rank %></td>
                <td class='rank_row'><%=  student.size %></td>
                <td class='rank_row'><%=  student.age %></td>
                <td class='address_row'><%=  student.address %> <%= student.city %> <%= student.zip %></td>
                <td class='phone_row'><%=  student.phone %></td>
                <td class='amount_row'><%= student.amount%></td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
      <div class="total_tution">
        <div class='price_wrapper'>
          <h1 id='total_price'>$<%= @grandTotal %></h1>
          <p>*before precent $<%= @total %> </p>
        </div>
        <div class='controls'>
          <a class="left-off-canvas-toggle button" href="#" >Quick Add</a>
          <%= link_to 'Add', '/students/new', :class => 'button' %>
          <p>Hide rows</p>
          <div class="row main">
            <div class='row'>
              <label>
                <input type="checkbox" id='rank_checkbox'>
                Rank
              </label>
            </div>
            <div class='row'>
              <label>
                <input type="checkbox" id='address_checkbox'>
                Address
              </label>
            </div>
            <div class="row">
              <label>
                <input type="checkbox" id='phone_checkbox'>
                Phone Number
              </label>
            </div>
            <div class='row'>
              <label>
                <input type="checkbox" id='amount_checkbox'>
                Amount
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a class="exit-off-canvas"></a>
  </div>

  <%= render :partial => 'static/search' %>

app/views/reports/inactive.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <aside class="left-off-canvas-menu">
    </aside>
    <div class="row">
      <div class="large-8 large-centered columns">
        <%# @totalFees %>
        <div class="header">
          <h1>Inactive Students</h1>
        </div>
        <table>
          <thead>
            <tr>
              <th>Student Name</th>
              <th>Rank</th>
              <th>Address</th>
              <th>Phone</th>
              <th>Amount</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
              <tr>
                <td><%=  link_to student.name, student_path(student) %> </td>
                <td><%=  student.rank %></td>
                <td><%=  student.address %></td>
                <td><%=  student.phone %></td>
                <td><%= student.amount%></td>
                <td><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <a class="exit-off-canvas"></a>
  </div>

  <%= render :partial => 'static/search' %>

app/views/reports/trails.html.erb
<div class="off-canvas-wrap" data-offcanvas>
  <div class="inner-wrap">
    <div class="row">
      <div class="large-8 large-centered columns">
        <%# @totalFees %>
        <div class="header">
          <h1>Trail Students </h1>
        </div>
        <table>
          <thead>
            <tr>
              <th>Student Name</th>
              <th class='rank_row'>Rank</th>
              <th class='rank_row'>Size</th>
              <th class='rank_row'>Age</th>
              <th class='address_row'>Address</th>
              <th class='phone_row'>Phone</th>
              <th class='amount_row'>Date</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
              <tr>
                <td><%=  link_to student.name, student_path(student) %> </td>
                <td class='rank_row'><%=  student.rank %></td>
                <td class='rank_row'><%=  student.size %></td>
                <td class='rank_row'><%=  student.age %></td>
                <td class='address_row'><%=  student.address %> <%= student.city %> <%= student.zip %></td>
                <td class='phone_row'><%=  student.phone %></td>
                <td class='amount_row'><%= student.trail%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <a class="exit-off-canvas"></a>
  </div>

  <%= render :partial => 'static/search' %>

app/views/transactions/index.html.erb
<h1>Point of Sale</h1>

<% @transactions.each do |t| %>
  <%= t.name  %>
<% end %>

app/views/transactions/new.html.erb
<div class="row student">
<h1>New Transaction</h1>


<%= form_for @transaction do |t| %>

  
 <% options = options_from_collection_for_select(@product, 'name', 'name') %>
 <%= t.label :name %>
 <%= t.text_field :name, :class => 'form-control',  data: { autocomplete: autocomplete_brand_name_products_path } %>
 
 <%= t.label :price %>
 <%= t.text_field :price %>

 <%= link_to('New Client', new_student_path, id: 'new') %>
 <%# options = options_from_collection_for_select(@student, 'id', 'name') %>
 <%# t.select :student_id, options, :class => 'form-control' %>

 <%= t.submit %>

<% end %>
</div>